### ISSUE TITLE
Missing Files causing container crash

### ISSUE THREAD

**Issue by MartinPezet** [CM2Walki/Squad#25]
When started the container will download all the required files from steam cmd, then stop with the below error:

``` 
Clearing Mods...
find: '/home/steam/squad-dedicated/SquadGame/Plugins/Mods/*': No such file or directory
bash: /home/steam/squad-dedicated/SquadGameServer.sh: No such file or directory
exited with code 127
```

This will not allow for persistent volumes either so I cannot give you what it has downloaded and what it hasn't

Here is my docker-compose:

```
version: "3"

services:
  squad:
    image: cm2network/squad
    stdin_open: true
    tty: true
    restart: always
    network_mode: "host"
    volumes:
      - /squad/:/home/steam/squad-dedicated/

    environment:
      - PORT=7787
      - QUERYPORT=27165
      - RCONPORT=21114
      - FIXEDMAXPLAYERS=80
      
    ports:
      - 7787:7787/tcp
      - 7788:7788/tcp
      - 27165:27165/tcp
      - 27166:27166/tcp
      - 21114:21114/tcp
      - 7787:7787/udp
      - 7788:7788/udp
      - 27165:27165/udp
      - 27166:27166/udp
      - 21114:21114/udp
```

Am I missing anything?
@CM2Walki
